apiVersion: v1
kind: Secret
metadata:
  name: cluster-private-anthos
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: cluster-private-anthos
  server: https://connectgateway.googleapis.com/v1beta1/projects/956404549410/locations/global/memberships/anthos-vmware-cluster
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": ["gcp"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": ""
      }
    }
